/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1iKlCCuUszQ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Image from "next/image";

interface AuthFormProps {
  title: string;
  description: string;
  image?: boolean;
  backButton: React.ComponentType<any>;
  children: React.ReactNode;
}

export function AuthForm({
  title,
  description,
  image,
  backButton: BackButton,
  children,
}: AuthFormProps) {
  return (
    <div className="w-[100vw] h-full flex flex-col justify-center lg:grid lg:min-h-[600px] lg:grid-cols-2 xl:min-h-[800px]">
      <div className="flex items-center justify-center py-12">
        <div className="mx-auto space-y-5 flex flex-col items-center max-w-[90vw]">
          <div className=" gap-2 text-center">
            <h1 className="text-2xl lg:text-3xl font-bold text-balance">
              {title}
            </h1>
            <p className="text-balance text-muted-foreground text-[16px] lg:text-[18px]">
              {description}
            </p>
          </div>
          {children}
          <div className="mt-4 text-center text-sm">
            <BackButton />
          </div>
        </div>
      </div>
      <div className="hidden bg-muted lg:block">
        {image && (
          <Image
            alt="Image"
            className="h-full w-full hidden lg:block object-cover dark:brightness-[0.2] dark:grayscale"
            height="1080"
            src="/placeholder.svg"
            style={{
              aspectRatio: "1920/1080",
              objectFit: "cover",
            }}
            width="1920"
          />
        )}
      </div>
    </div>
  );
}
