/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ac7iuASUpk9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import { Children } from "react";

interface AddItemFormProps {
  title: string;
  description: string;
  children: React.ReactNode;
}

export function AddItemForm({
  title,
  description,
  children,
}: AddItemFormProps) {
  return (
    <div className="flex h-full items-center justify-center rounded-lg border border-dashed shadow-sm">
      <div className="flex flex-col items-center gap-1 text-center">
        <h3 className="text-2xl font-bold tracking-tight">{title}</h3>
        <p className="text-sm text-muted-foreground text-balance">
          {description}
        </p>
        {children}
      </div>
    </div>
  );
}
